# Generated by Django 5.2.11 on 2026-03-17 18:20

from django.db import migrations, models


def assign_legacy_company(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    ServiceRegistry = apps.get_model("services", "ServiceRegistry")

    company, _ = Company.objects.get_or_create(
        code="legacy-default",
        defaults={
            "name": "Legacy Default Company",
            "is_active": True,
        },
    )
    ServiceRegistry.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_smartphone_and_organization_models"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceregistry",
            name="company",
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name="services_serviceregistrys", to="accounts.company"),
        ),
        migrations.AlterField(
            model_name="serviceregistry",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceregistry",
            name="code",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceregistry",
            name="base_path",
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(assign_legacy_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="serviceregistry",
            name="company",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="services_serviceregistrys", to="accounts.company"),
        ),
        migrations.AlterModelOptions(
            name="serviceregistry",
            options={
                "verbose_name": "service registry entry",
                "verbose_name_plural": "service registry entries",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="serviceregistry",
            constraint=models.UniqueConstraint(fields=("company", "code"), name="uniq_service_code_per_company"),
        ),
        migrations.AddConstraint(
            model_name="serviceregistry",
            constraint=models.UniqueConstraint(fields=("company", "base_path"), name="uniq_service_base_path_per_company"),
        ),
    ]
