# Generated by Django 5.2.11 on 2026-03-18 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name'),
        ('services', '0002_company_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='RegisteredApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_code', models.SlugField(max_length=100, unique=True)),
                ('app_name', models.CharField(max_length=200)),
                ('app_description', models.TextField(blank=True)),
                ('app_domain', models.CharField(max_length=255)),
                ('app_base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_sso', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.company')),
            ],
            options={
                'verbose_name': 'registered application',
                'verbose_name_plural': 'registered applications',
                'ordering': ['company__name', 'app_name'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredScreen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_code', models.SlugField(max_length=100)),
                ('screen_name', models.CharField(max_length=200)),
                ('route_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='services.registeredapplication')),
            ],
            options={
                'verbose_name': 'registered screen',
                'verbose_name_plural': 'registered screens',
                'ordering': ['application__app_name', 'screen_name'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_code', models.SlugField(max_length=100)),
                ('feature_name', models.CharField(max_length=200)),
                ('feature_type', models.CharField(choices=[('view', 'View'), ('action', 'Action'), ('api', 'API'), ('automation', 'Automation')], default='view', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.registeredapplication')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.registeredscreen')),
            ],
            options={
                'verbose_name': 'registered feature',
                'verbose_name_plural': 'registered features',
                'ordering': ['application__app_name', 'feature_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='registeredscreen',
            constraint=models.UniqueConstraint(fields=('application', 'screen_code'), name='uniq_screen_code_per_application'),
        ),
        migrations.AddConstraint(
            model_name='registeredscreen',
            constraint=models.UniqueConstraint(fields=('application', 'route_path'), name='uniq_screen_route_per_application'),
        ),
        migrations.AddConstraint(
            model_name='registeredfeature',
            constraint=models.UniqueConstraint(fields=('application', 'feature_code'), name='uniq_feature_code_per_application'),
        ),
    ]
