# Generated by Django 5.2.11 on 2026-03-17 18:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="smartphone_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("company", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="departments", to="accounts.company")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserCompanyMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")], default="member", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("company", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="user_memberships", to="accounts.company")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="company_memberships", to="accounts.user")),
            ],
            options={
                "verbose_name": "user company membership",
                "verbose_name_plural": "user company memberships",
                "ordering": ["company__name", "user__email"],
            },
        ),
        migrations.CreateModel(
            name="UserDepartmentMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("manager", "Manager"), ("member", "Member")], default="member", max_length=20)),
                ("department", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="user_memberships", to="accounts.department")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="department_memberships", to="accounts.user")),
            ],
            options={
                "verbose_name": "user department membership",
                "verbose_name_plural": "user department memberships",
                "ordering": ["department__company__name", "department__name", "user__email"],
            },
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(fields=("company", "code"), name="uniq_department_code_per_company"),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="uniq_department_name_per_company"),
        ),
        migrations.AddConstraint(
            model_name="usercompanymembership",
            constraint=models.UniqueConstraint(fields=("user", "company"), name="uniq_user_company_membership"),
        ),
        migrations.AddConstraint(
            model_name="userdepartmentmembership",
            constraint=models.UniqueConstraint(fields=("user", "department"), name="uniq_user_department_membership"),
        ),
    ]
