from dataclasses import dataclass, field


@dataclass(frozen=True)
class DocumentEntry:
    slug: str
    title: str
    file_path: str
    summary: str
    category: str
    audience: tuple[str, ...]
    sort_order: int
    is_featured: bool = False
    is_core: bool = False
    show_in_index: bool = True
    related_slugs: tuple[str, ...] = field(default_factory=tuple)
    status_label: str = "Active"
    reading_order: int | None = None
    icon_key: str = "doc"


DOCUMENT_REGISTRY: tuple[DocumentEntry, ...] = (
    DocumentEntry(
        slug="platform-overview",
        title="Platform Overview",
        file_path="platform-overview.md",
        summary="Start here for ThePeach purpose, operating model, and the platform responsibilities shared across services.",
        category="platform-foundations",
        audience=("developer", "operator", "maintainer"),
        sort_order=10,
        is_featured=True,
        is_core=True,
        related_slugs=("architecture-principles", "project-structure-and-conventions"),
        status_label="Core",
        reading_order=10,
        icon_key="overview",
    ),
    DocumentEntry(
        slug="architecture-principles",
        title="Architecture Principles",
        file_path="architecture-principles.md",
        summary="API-first, SSO-first, reusable, loosely coupled, and AI-ready platform design rules.",
        category="platform-foundations",
        audience=("developer", "maintainer", "integrator"),
        sort_order=20,
        is_featured=True,
        is_core=True,
        related_slugs=("platform-overview", "project-structure-and-conventions", "api-and-gateway-standards"),
        status_label="Core",
        reading_order=20,
        icon_key="architecture",
    ),
    DocumentEntry(
        slug="project-structure-and-conventions",
        title="Project Structure And Conventions",
        file_path="project-structure-and-conventions.md",
        summary="Repository layout, app ownership, settings strategy, and conventions for extending ThePeach safely.",
        category="platform-foundations",
        audience=("developer", "maintainer"),
        sort_order=30,
        is_core=True,
        related_slugs=("platform-overview", "architecture-principles", "repository-management"),
        status_label="Core",
        reading_order=30,
        icon_key="structure",
    ),
    DocumentEntry(
        slug="central-auth-and-application-registry",
        title="Central Auth And Application Registry",
        file_path="central-auth-and-application-registry.md",
        summary="Centralized identity, JWT direction, application registration, and the current SSO evolution path.",
        category="authentication-identity",
        audience=("developer", "integrator", "operator"),
        sort_order=40,
        is_featured=True,
        is_core=True,
        related_slugs=("architecture-principles", "api-and-gateway-standards", "production-deployment"),
        status_label="Core",
        reading_order=40,
        icon_key="auth",
    ),
    DocumentEntry(
        slug="api-and-gateway-standards",
        title="API And Gateway Standards",
        file_path="api-and-gateway-standards.md",
        summary="Versioning, response envelopes, deterministic contracts, and the gateway role for integration and AI usage.",
        category="api-integration",
        audience=("developer", "integrator", "maintainer"),
        sort_order=50,
        is_featured=True,
        is_core=True,
        related_slugs=("architecture-principles", "central-auth-and-application-registry", "shared-media-server"),
        status_label="Core",
        reading_order=50,
        icon_key="api",
    ),
    DocumentEntry(
        slug="shared-media-server",
        title="Shared Media Server",
        file_path="shared-media-server.md",
        summary="Centralized shared image storage, reusable URLs, deduplication, and operator-facing media workflows.",
        category="media-assets",
        audience=("developer", "operator", "integrator"),
        sort_order=60,
        is_featured=True,
        related_slugs=("api-and-gateway-standards", "production-deployment", "logging-and-operations"),
        status_label="Active",
        reading_order=60,
        icon_key="media",
    ),
    DocumentEntry(
        slug="logging-and-operations",
        title="Logging And Operations",
        file_path="logging-and-operations.md",
        summary="Operational logging, auditability, backup expectations, and production observability principles.",
        category="operations-deployment",
        audience=("operator", "maintainer"),
        sort_order=70,
        is_core=True,
        related_slugs=("production-deployment", "repository-management", "shared-media-server"),
        status_label="Operational",
        reading_order=70,
        icon_key="operations",
    ),
    DocumentEntry(
        slug="production-deployment",
        title="Production Deployment",
        file_path="production-deployment.md",
        summary="Cloudflare, Nginx, Gunicorn, Django, PostgreSQL, and release/rollback notes for production operations.",
        category="operations-deployment",
        audience=("operator", "maintainer"),
        sort_order=80,
        is_featured=True,
        is_core=True,
        related_slugs=("logging-and-operations", "repository-management", "shared-media-server"),
        status_label="Operational",
        reading_order=80,
        icon_key="deployment",
    ),
    DocumentEntry(
        slug="public-internal-split",
        title="Public And Internal Split",
        file_path="public-internal-split.md",
        summary="Public domain APIs stay available while admin, internal auth, and gateway operations move behind protected ops hosts.",
        category="operations-deployment",
        audience=("operator", "maintainer", "developer"),
        sort_order=85,
        is_core=True,
        related_slugs=("central-auth-and-application-registry", "api-and-gateway-standards", "production-deployment"),
        status_label="Operational",
        reading_order=85,
        icon_key="deployment",
    ),
    DocumentEntry(
        slug="repository-management",
        title="Repository Management",
        file_path="repository-management.md",
        summary="Branch strategy, commit conventions, GitHub usage, and repository rollback discipline.",
        category="repository-workflow",
        audience=("developer", "maintainer"),
        sort_order=90,
        related_slugs=("project-structure-and-conventions", "production-deployment"),
        status_label="Operational",
        reading_order=90,
        icon_key="repo",
    ),
    DocumentEntry(
        slug="platform-documentation-system",
        title="Platform Documentation System",
        file_path="platform-documentation-system.md",
        summary="How the documentation registry, slug mapping, markdown rendering, and portal structure are maintained.",
        category="references",
        audience=("developer", "maintainer"),
        sort_order=100,
        related_slugs=("repository-management", "platform-overview"),
        status_label="Reference",
        reading_order=100,
        icon_key="docs",
    ),
)
