# Generated by Django 5.2.11 on 2026-03-17 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('source', models.CharField(db_index=True, max_length=128)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='logs_system_level_2b79e0_idx'), models.Index(fields=['source', 'created_at'], name='logs_system_source_42f165_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status_code', models.PositiveIntegerField()),
                ('duration_ms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='logs_apireq_path_d05ea0_idx'), models.Index(fields=['status_code', 'created_at'], name='logs_apireq_status__086eab_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('token_refresh', 'Token Refresh'), ('token_verify', 'Token Verify'), ('failure', 'Failure')], db_index=True, max_length=32)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='logs_authev_event_t_476c83_idx'), models.Index(fields=['success', 'created_at'], name='logs_authev_success_6b6d3c_idx')],
            },
        ),
    ]
