# Generated by Django 5.2.11 on 2026-03-17 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('logo', 'Logo'), ('video', 'Video')], db_index=True, max_length=20)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('embed', 'Embed')], default='url', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/%Y/%m/')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('embed_url', models.URLField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_reusable', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['asset_type', 'is_public'], name='media_media_asset_t_fe6a05_idx'), models.Index(fields=['asset_type', 'is_reusable'], name='media_media_asset_t_dd5bc6_idx')],
            },
        ),
    ]
