# Generated by Django 5.2.11 on 2026-03-17 18:20

from django.db import migrations, models


def assign_legacy_company(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    MediaAsset = apps.get_model("media", "MediaAsset")

    company, _ = Company.objects.get_or_create(
        code="legacy-default",
        defaults={
            "name": "Legacy Default Company",
            "is_active": True,
        },
    )
    MediaAsset.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_smartphone_and_organization_models"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="company",
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name="media_mediaassets", to="accounts.company"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.RunPython(assign_legacy_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mediaasset",
            name="company",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="media_mediaassets", to="accounts.company"),
        ),
        migrations.AlterModelOptions(
            name="mediaasset",
            options={"ordering": ["company__name", "title"]},
        ),
        migrations.RemoveIndex(
            model_name="mediaasset",
            name="media_media_asset_t_fe6a05_idx",
        ),
        migrations.RemoveIndex(
            model_name="mediaasset",
            name="media_media_asset_t_dd5bc6_idx",
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["company", "asset_type", "is_public"], name="media_company_public_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["company", "asset_type", "is_reusable"], name="media_company_reusable_idx"),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(fields=("company", "slug"), name="uniq_media_slug_per_company"),
        ),
    ]
