# Generated by Django 5.2.11 on 2026-03-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name'),
        ('media', '0002_company_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.company'),
        ),
    ]
