# Generated by Django 5.2.11 on 2026-03-18 06:52

import django.db.models.deletion
import media.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediaasset_company'),
        ('services', '0003_alter_serviceregistry_company_registeredapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLogoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_code', models.SlugField(max_length=100, unique=True)),
                ('logo_name', models.CharField(max_length=200)),
                ('original_file_name', models.CharField(max_length=255)),
                ('image_file', models.FileField(upload_to=media.models.platform_logo_upload_to)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('usage_type', models.CharField(choices=[('primary', 'Primary'), ('header', 'Header'), ('icon', 'Icon'), ('dark_mode', 'Dark Mode'), ('light_mode', 'Light Mode')], default='primary', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logo_assets', to='services.registeredapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logo_assets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_logo_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application__app_name', 'logo_name'],
                'indexes': [models.Index(fields=['application', 'is_active'], name='logo_app_active_idx'), models.Index(fields=['application', 'usage_type'], name='logo_app_usage_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('usage_type', 'primary')), fields=('application', 'usage_type'), name='uniq_active_primary_logo_per_application')],
            },
        ),
    ]
